version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.24.4
    - 5.25.0
    - 5.26.0
    - 5.26.3
    - 5.27.0
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.7.0
    - 7.8.0
  - dependency-name: postcss-url
    versions:
    - 10.1.1
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: postcss-import
    versions:
    - 14.0.0
  - dependency-name: htmlparser2
    versions:
    - 6.0.1
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.3
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: irc-framework
    versions:
    - 4.9.0
  - dependency-name: css-vars-ponyfill
    versions:
    - 2.4.3
  - dependency-name: vue-template-compiler
    versions:
    - 2.6.12
  - dependency-name: vue
    versions:
    - 2.6.12
  - dependency-name: "@vue/eslint-config-airbnb"
    versions:
    - 5.3.0
  - dependency-name: xhr
    versions:
    - 2.6.0
  - dependency-name: ip-regex
    versions:
    - 4.3.0
  - dependency-name: "@babel/runtime-corejs3"
    versions:
    - 7.12.5
  - dependency-name: "@vue/cli-plugin-unit-jest"
    versions:
    - 4.5.11
  - dependency-name: vue-virtual-scroller
    versions:
    - 1.0.10
  - dependency-name: less-loader
    versions:
    - 8.0.0
